name: Black code formatter

on:
  pull_request:
    branches: [ master ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Black Code Formatter
        uses: lgeiger/black-action@v1.0.1
        with:
          args: ". --check"
